version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    ignore:
      # Prevent automatic updates for core libraries and tightly coupled ecosystem dependencies to reduce breakage
      - dependency-name: react-native
      - dependency-name: react
      - dependency-name: react-native/babel-preset
      - dependency-name: react-native/metro-config
      - dependency-name: react-native/typescript-config
      - dependency-name: react-native/eslint-config
      - dependency-name: react-navigation/native
      - dependency-name: react-navigation/native-stack
      - dependency-name: react-native-safe-area-context
      - dependency-name: react-native-screens
      - dependency-name: types/react
      - dependency-name: types/jest
      - dependency-name: eslint
      - dependency-name: prettier
      - dependency-name: eslint-plugin-prettier
      - dependency-name: eslint-config-prettier
      - dependency-name: commitlint
      - dependency-name: commitlint/config-conventional
      - dependency-name: release-it
      - dependency-name: release-it/conventional-changelog
      - dependency-name: evilmartians/lefthook
    groups:
      npm-dependencies:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /example
    schedule:
      interval: weekly
      day: monday
    ignore:
      # Prevent automatic updates for core libraries and tightly coupled ecosystem dependencies to reduce breakage
      - dependency-name: react-native
      - dependency-name: react
      - dependency-name: react-native/babel-preset
      - dependency-name: react-native/metro-config
      - dependency-name: react-native/typescript-config
      - dependency-name: react-native/eslint-config
      - dependency-name: react-navigation/native
      - dependency-name: react-navigation/native-stack
      - dependency-name: react-native-safe-area-context
      - dependency-name: react-native-screens
      - dependency-name: types/react
      - dependency-name: types/jest
      - dependency-name: eslint
      - dependency-name: prettier
      - dependency-name: eslint-plugin-prettier
      - dependency-name: eslint-config-prettier
      - dependency-name: commitlint
      - dependency-name: commitlint/config-conventional
      - dependency-name: release-it
      - dependency-name: release-it/conventional-changelog
      - dependency-name: evilmartians/lefthook
    groups:
      npm-example-dependencies:
        patterns:
          - '*'

  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: weekly
      day: monday
    groups:
      gradle-dependencies:
        patterns:
          - '*'

  - package-ecosystem: gradle
    directory: /example/android
    schedule:
      interval: weekly
      day: monday
    groups:
      gradle-example-dependencies:
        patterns:
          - '*'
