version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 0
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: '@babel/core'
      - dependency-name: brace-expansion
      - dependency-name: fast-uri
      - dependency-name: joi
      - dependency-name: js-yaml
      - dependency-name: shell-quote
      - dependency-name: tar
      - dependency-name: turbo
      - dependency-name: vm2
      - dependency-name: ws
  - package-ecosystem: gradle
    open-pull-requests-limit: 0
    directory: /android
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    open-pull-requests-limit: 5
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'
