version: 2

# Shared ignore list for preventing automatic updates for core libraries
x-ignore-common: &ignore-common
  - dependency-name: react
  - dependency-name: react-native
  - dependency-name: react-native/babel-preset
  - dependency-name: react-native/metro-config
  - dependency-name: react-native/typescript-config
  - dependency-name: react-native/eslint-config
  - dependency-name: react-navigation/native
  - dependency-name: react-navigation/native-stack
  - dependency-name: react-native-safe-area-context
  - dependency-name: react-native-screens

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    ignore: *ignore-common
    groups:
      npm-dependencies:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /example
    schedule:
      interval: weekly
      day: monday
    ignore: *ignore-common
    groups:
      npm-example-dependencies:
        patterns:
          - '*'

  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: weekly
      day: monday
    groups:
      gradle-dependencies:
        patterns:
          - '*'

  - package-ecosystem: gradle
    directory: /example/android
    schedule:
      interval: weekly
      day: monday
    groups:
      gradle-example-dependencies:
        patterns:
          - '*'
