version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    ignore:
      # Ignore updates for react-native in the root directory
      - dependency-name: react-native
      # Ignore updates for react in the root directory
      - dependency-name: react
    groups:
      npm-dependencies:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /example
    schedule:
      interval: weekly
      day: monday
    ignore:
      # Ignore updates for react-native in the example directory
      - dependency-name: react-native
      # Ignore updates for react in the example directory
      - dependency-name: react
    groups:
      npm-example-dependencies:
        patterns:
          - '*'

  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: weekly
      day: monday
    groups:
      gradle-dependencies:
        patterns:
          - '*'

  - package-ecosystem: gradle
    directory: /example/android
    schedule:
      interval: weekly
      day: monday
    groups:
      gradle-example-dependencies:
        patterns:
          - '*'
