# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end
# for development alongside ../../react-native-smile-id.podspec uncomment the version and specify
# tag or branch in here DO NOT MERGE THIS TO main branch
# pod 'SmileID', git: 'https://github.com/smileidentity/ios.git', branch: 'main'
target 'SmileIdExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'SmileIdExampleTests' do
    inherit! :complete
    # Pods for testing
  end

post_install do |installer|
  # Fix Sentry SDK 8.55.0 build issue
  # The capture(userFeedback:) method has a broken reference
  # to SentrySDKInternal
  sentry_sdk_path = "#{installer.sandbox.root}/Sentry/Sources/Swift/Helper/SentrySDK.swift"

    next unless File.exist?(sentry_sdk_path)
    next unless File.writable?(sentry_sdk_path)

    contents = File.read(sentry_sdk_path)

    patched = contents.gsub(
      'SentrySDK.capture(userFeedback)',
      '// SentrySDK.capture(userFeedback)'
    )

    File.write(sentry_sdk_path, patched)
  end

  # Fix SmileID Swift module interface verification error
  installer.pods_project.targets.each do |target|
    if target.name == 'SmileID'
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
      end
    end
  end

  # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false,
    # :ccache_enabled => true
  )
end
end
