name: 'ci'

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

      - name: Run unit tests
        run: yarn test --maxWorkers=2 --coverage

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn prepack

  build-examples:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        platform: [android, ios]
    env:
      TURBO_CACHE_DIR: .turbo/${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Cache turborepo
        uses: actions/cache@v4
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          key: ${{ runner.os }}-turborepo-${{ matrix.platform }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-turborepo-${{ matrix.platform }}-

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
            **/ios/Pods
          key: ${{ runner.os }}-${{ matrix.platform }}-deps-${{ hashFiles('example/android/gradle/wrapper/gradle-wrapper.properties', 'example/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.platform }}-deps-

      - name: Set up JDK (Android)
        if: matrix.platform == 'android'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Xcode (iOS)
        if: matrix.platform == 'ios'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.2

      - name: Install cocoapods (iOS)
        if: matrix.platform == 'ios'
        run: yarn example pods
        env:
          NO_FLIPPER: 1

      - name: Build example
        run: yarn turbo run build:${{ matrix.platform }} --cache-dir="${{ env.TURBO_CACHE_DIR }}" --no-cache
